//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiVietCaNhanAnh
    {
        public int Id { get; set; }
        public Nullable<int> BaiVietId { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual BaiVietCaNhan BaiVietCaNhan { get; set; }
    }
}
