//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiVietCaNhan
    {
        public BaiVietCaNhan()
        {
            this.BaiVietCaNhanAnhs = new HashSet<BaiVietCaNhanAnh>();
            this.BaiVietCaNhanBaoCaos = new HashSet<BaiVietCaNhanBaoCao>();
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ChuBaiVietId { get; set; }
        public string NoiDungBaiViet { get; set; }
        public byte[] Media { get; set; }
        public byte[] MediaThumb { get; set; }
        public string BinhLuanIds { get; set; }
        public string NguoiThichIds { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ICollection<BaiVietCaNhanAnh> BaiVietCaNhanAnhs { get; set; }
        public virtual ICollection<BaiVietCaNhanBaoCao> BaiVietCaNhanBaoCaos { get; set; }
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}
